This is a regression task that is designed to forecast the global active power  of a household.  
The dataset used to train the models is the [Individual Household Electric Power Consumption](https://archive.ics.uci.edu/dataset/235/individual+household+electric+power+consumption) from UCI Machine Learning Repository

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('household_power_consumption.txt', sep=';', low_memory=False)

print(data.head())

         Date      Time Global_active_power Global_reactive_power  Voltage  \
0  16/12/2006  17:24:00               4.216                 0.418  234.840
1  16/12/2006  17:25:00               5.360                 0.436  233.630
2  16/12/2006  17:26:00               5.374                 0.498  233.290
3  16/12/2006  17:27:00               5.388                 0.502  233.740
4  16/12/2006  17:28:00               3.666                 0.528  235.680

  Global_intensity Sub_metering_1 Sub_metering_2  Sub_metering_3
0           18.400          0.000          1.000            17.0
1           23.000          0.000          1.000            16.0
2           23.000          0.000          2.000            17.0
3           23.000          0.000          1.000            17.0
4           15.800          0.000          1.000            17.0

In [3]:
print(data.info(show_counts=True))

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Date                   2075259 non-null  str
 1   Time                   2075259 non-null  str
 2   Global_active_power    2075259 non-null  str
 3   Global_reactive_power  2075259 non-null  str
 4   Voltage                2075259 non-null  str
 5   Global_intensity       2075259 non-null  str
 6   Sub_metering_1         2075259 non-null  str
 7   Sub_metering_2         2075259 non-null  str
 8   Sub_metering_3         2049280 non-null  float64
dtypes: float64(1), str(8)
memory usage: 142.5 MB
None

In [4]:
print(data.describe())

       Sub_metering_3
count    2.049280e+06
mean     6.458447e+00
std      8.437154e+00
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.700000e+01
max      3.100000e+01

In [5]:
print(data.count())

Date                     2075259
Time                     2075259
Global_active_power      2075259
Global_reactive_power    2075259
Voltage                  2075259
Global_intensity         2075259
Sub_metering_1           2075259
Sub_metering_2           2075259
Sub_metering_3           2049280
dtype: int64

In [6]:
print((data['Global_active_power'] == '?').sum())

25979

In [7]:
cols = data.columns.tolist()
print(cols)

['Date', 'Time', 'Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3']

In [8]:
for col in cols:
    empty_count = (data[col] == '?').sum()
    print('Missing values in ' + col + ' = ' + str(empty_count))

Missing values in Date = 0
Missing values in Time = 0
Missing values in Global_active_power = 25979
Missing values in Global_reactive_power = 25979
Missing values in Voltage = 25979
Missing values in Global_intensity = 25979
Missing values in Sub_metering_1 = 25979
Missing values in Sub_metering_2 = 25979
Missing values in Sub_metering_3 = 0

In [ ]:
# converting "?" into np.nan
cols_containing_missing = ['Global_active_power', 'Global_reactive_power', 'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2']

data[cols_containing_missing] = data[cols_containing_missing].replace('?', np.nan)
print(data.info(show_counts=True))

Date                     2075259
Time                     2075259
Global_active_power      2049280
Global_reactive_power    2049280
Voltage                  2049280
Global_intensity         2049280
Sub_metering_1           2049280
Sub_metering_2           2049280
Sub_metering_3           2049280
dtype: int64

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Date                   2075259 non-null  str
 1   Time                   2075259 non-null  str
 2   Global_active_power    2049280 non-null  str
 3   Global_reactive_power  2049280 non-null  str
 4   Voltage                2049280 non-null  str
 5   Global_intensity       2049280 non-null  str
 6   Sub_metering_1         2049280 non-null  str
 7   Sub_metering_2         2049280 non-null  str
 8   Sub_metering_3         2049280 non-null  float64
dtypes: float64(1), str(8)
memory usage: 142.5 MB
None

In [11]:
data.dropna(inplace=True)

print(data.info(show_counts=True))

<class 'pandas.DataFrame'>
Index: 2049280 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Date                   2049280 non-null  str
 1   Time                   2049280 non-null  str
 2   Global_active_power    2049280 non-null  str
 3   Global_reactive_power  2049280 non-null  str
 4   Voltage                2049280 non-null  str
 5   Global_intensity       2049280 non-null  str
 6   Sub_metering_1         2049280 non-null  str
 7   Sub_metering_2         2049280 non-null  str
 8   Sub_metering_3         2049280 non-null  float64
dtypes: float64(1), str(8)
memory usage: 156.3 MB
None

In [14]:
print(data['Global_active_power'][0])

4.216

In [16]:
test = pd.to_numeric(data['Global_active_power'][0], errors='raise')
type(test)

numpy.float64

In [17]:
for col in cols_containing_missing:
    data[col] = pd.to_numeric(data[col])

print(data.info(show_counts=True))

<class 'pandas.DataFrame'>
Index: 2049280 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Date                   2049280 non-null  str
 1   Time                   2049280 non-null  str
 2   Global_active_power    2049280 non-null  float64
 3   Global_reactive_power  2049280 non-null  float64
 4   Voltage                2049280 non-null  float64
 5   Global_intensity       2049280 non-null  float64
 6   Sub_metering_1         2049280 non-null  float64
 7   Sub_metering_2         2049280 non-null  float64
 8   Sub_metering_3         2049280 non-null  float64
dtypes: float64(7), str(2)
memory usage: 156.3 MB
None

Separate the target variable from the independant variables

In [21]:
X = data.drop(columns=['Global_active_power'])
target = data['Global_active_power']

X.head()

,Date,Time,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,0.418,234.84,18.4,0.0,1.0,17.0
1,16/12/2006,17:25:00,0.436,233.63,23.0,0.0,1.0,16.0
2,16/12/2006,17:26:00,0.498,233.29,23.0,0.0,2.0,17.0
3,16/12/2006,17:27:00,0.502,233.74,23.0,0.0,1.0,17.0
4,16/12/2006,17:28:00,0.528,235.68,15.8,0.0,1.0,17.0

Processing date and time

In [23]:
X['Date'] = pd.to_datetime(X['Date'])

C:\Users\User\AppData\Local\Temp\ipykernel_22780\2910584453.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  X['Date'] = pd.to_datetime(X['Date'])

In [24]:
X['Date'].head(2)

0   2006-12-16
1   2006-12-16
Name: Date, dtype: datetime64[us]

In [26]:
X['month'] = X['Date'].dt.month
X['day'] = X['Date'].dt.day
X['year'] = X['Date'].dt.year
X['Day_of_week'] = X['Date'].dt.dayofweek
X['Week_of_year'] = X['Date'].dt.isocalendar().week

X.head(2)

,Date,Time,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,month,day,year,Day_of_week,Week_of_year
0,2006-12-16,17:24:00,0.418,234.84,18.4,0.0,1.0,17.0,12,16,2006,5,50
1,2006-12-16,17:25:00,0.436,233.63,23.0,0.0,1.0,16.0,12,16,2006,5,50

In [27]:
# drop the date column since all its necessary informations are extracted

X.drop(columns=['Date'], inplace=True)
X.head(2)

,Time,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,month,day,year,Day_of_week,Week_of_year
0,17:24:00,0.418,234.84,18.4,0.0,1.0,17.0,12,16,2006,5,50
1,17:25:00,0.436,233.63,23.0,0.0,1.0,16.0,12,16,2006,5,50

In [29]:
# convert the time feature into datetime since it's an str type

X['Time'] = pd.to_datetime(X['Time'])
type(X['Time'])

C:\Users\User\AppData\Local\Temp\ipykernel_22780\129655232.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  X['Time'] = pd.to_datetime(X['Time'])

pandas.Series

In [30]:
# extract necessary informations from the time feature

X['Hour'] = X['Time'].dt.hour
X['Minute'] = X['Time'].dt.minute

X.head(2)

,Time,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,month,day,year,Day_of_week,Week_of_year,Hour,Minute
0,2026-05-27 17:24:00,0.418,234.84,18.4,0.0,1.0,17.0,12,16,2006,5,50,17,24
1,2026-05-27 17:25:00,0.436,233.63,23.0,0.0,1.0,16.0,12,16,2006,5,50,17,25

In [ ]:
# drop the Time feature

X.drop(columns=['Time'], inplace=True)

X.head(1)